
class AppGreetingString {
  static List<Map<String, dynamic>> greetings = [
    {
      "time": "morning",
      "greeting": {
        "en": "Good Morning",
        "ur": "صبح بخیر",
        "hi": "गुड मॉर्निंग",
        "ps": "سهار مو پخير",
        "ar": "صباح الخير",
        "bn": "শুভ সকাল",
        "my": "မင်္ဂလာပါ",
        "cs": "Dobré ráno",
        "zh": "早上好",
        "da": "Godmorgen",
        "nl": "Goedemorgen",
        "fil": "Magandang Umaga",
        "fr": "Bonjour",
        "de": "Guten Morgen",
        "el": "Καλημέρα",
        "gu": "સુપ્રભાત",
        "ha": "Ina kwana",
        "he": "בוקר טוב",
        "hu": "Jó reggelt",
        "id": "Selamat Pagi",
        "fa": "صبح بخیر",
        "pl": "Dzień dobry",
        "pt": "Bom Dia",
        "pa": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
        "it": "Buongiorno",
        "ja": "おはようございます",
        "jv": "Sugeng Enjing",
        "ko": "좋은 아침입니다",
        "ms": "Selamat Pagi",
        "no": "God Morgen",
        "ru": "Доброе утро",
        "ro": "Bună dimineața",
        "si": "සුභ උදෑසනක්",
        "es": "Buenos Días",
        "sw": "Habari ya asubuhi",
        "sv": "God morgon",
        "ta": "காலை வணக்கம்",
        "te": "శుభోదయం",
        "th": "สวัสดีตอนเช้า",
        "tr": "Günaydın",
        "uk": "Добро ранку",
        "vi": "Chào buổi sáng",
        "fi": "Hyvää huomenta",
        "ml": "സുപ്രഭാതം",
        "sk": "Dobré ráno",
        "ca": "Bon dia",
        "sr": "Добро јутро",
        "hr": "Dobro jutro",
        "lt": "Labas rytas",
        "sl": "Dobro jutro",
        "is": "Góðan morgun",
        "eu": "Egun on",
        "gl": "Bo día",
        "mk": "Добро утро",
        "ne": "शुभ बिहान",
        "km": "សួស្តីព្រឹក",
        "am": "ሰላም ዕረፍ",
        "yo": "E kaaro",
        "tg": "Субҳи хуш",
        "hmn": "Zoo siab tos txais",
        "fj": "Bula",
        "su": "Wilujeng Sumping",
        "tt": "Иртем белән",
        "mn": "Сайн байна уу",
        "mt": "Bongu",
        "mg": "Salama",
        "wo": "Jaamu",
        "qu": "Ñukaka sumaq p'unchay",
        "xh": "Ubusuku obuhle",
        "zu": "Sawubona",
        "hy": "Բարի լույս",
        "ba": "Иртәнге хәерле",
        "br": "Demat",
        "se": "Buorre beaivi",
        "tw": "Meda wo akye",
        "co": "Bonghjornu",
        "gd": "Madainn mhath"
      }
    },
    {
      "time": "afternoon",
      "greeting": {
        "en": "Good Afternoon",
        "ur": "دوپہر بخیر",
        "hi": "गुड आफ्टरनून",
        "ps": "مازیګر مو پخير",
        "ar": "مساء الخير",
        "bn": "শুভ অপরাহ্ন",
        "my": "ညနေခင်းမှာ",
        "cs": "Dobré odpoledne",
        "zh": "下午好",
        "da": "God eftermiddag",
        "nl": "Goedemiddag",
        "fil": "Magandang Hapon",
        "fr": "Bon Après-midi",
        "de": "Guten Nachmittag",
        "el": "Καλησπέρα",
        "gu": "મધ્યાહ્નની શુભેચ્છા",
        "ha": "Barka da yamma",
        "he": "אחר צהריים טובים",
        "hu": "Jó napot",
        "id": "Selamat Siang",
        "fa": "عصر بخیر",
        "pl": "Dzień dobry",
        "pt": "Boa Tarde",
        "pa": "ਸ਼ਾਮ ਦਾ ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
        "it": "Buon pomeriggio",
        "ja": "こんにちは",
        "jv": "Sugeng siang",
        "ko": "좋은 오후입니다",
        "ms": "Selamat Petang",
        "no": "God ettermiddag",
        "ru": "Добрый день",
        "ro": "Bună după-amiaza",
        "si": "සුභ පස්වරුවක්",
        "es": "Buenas Tardes",
        "sw": "Habari ya mchana",
        "sv": "God eftermiddag",
        "ta": "மதிய வணக்கம்",
        "te": "మధ్యాహ్న శుభాకాంక్షలు",
        "th": "สวัสดีตอนบ่าย",
        "tr": "İyi günler",
        "uk": "Добрий день",
        "vi": "Chào buổi chiều",
        "fi": "Hyvää iltapäivää",
        "ml": "ഉച്ചഭക്ഷണം",
        "sk": "Dobré popoludnie",
        "ca": "Bona tarda",
        "sr": "Добро поподне",
        "hr": "Dobar dan",
        "lt": "Laba popietė",
        "sl": "Dober dan",
        "is": "Gott eftir hádegi",
        "eu": "Arratsalde on",
        "gl": "Boa tarde",
        "mk": "Добро попладне",
        "ne": "शुभ अपराह्न",
        "km": "សួស្តីល្ងាច",
        "am": "የእለት ገና",
        "yo": "E ku asiko",
        "tg": "Беҳтарин",
        "hmn": "Zoo siab",
        "fj": "Yadra",
        "su": "Wilujeng sonten",
        "tt": "Кичке рәхим итегез",
        "mn": "Өглөөний мэнд",
        "mt": "Bongu",
        "mg": "Tsy adino",
        "wo": "Jaamu",
        "qu": "Ñukaka sumaq",
        "xh": "Ubusuku obuhle",
        "zu": "Sawubona",
        "hy": "Բարի օր",
        "ba": "Кичке хәерле",
        "br": "Mat",
        "se": "Buorre eahket",
        "tw": "Meda wo akye",
        "tl": "Magandang Hapon",
      }
    },
    {
      "time": "evening",
      "greeting": {
        "en": "Good Evening",
        "ur": "شام بخیر",
        "hi": "गुड ईवनिंग",
        "ps": "ماښام مو پخير",
        "ar": "مساء الخير",
        "bn": "শুভ সন্ধ্যা",
        "my": "ညဘက်မှာ",
        "cs": "Dobrý večer",
        "zh": "晚上好",
        "da": "God aften",
        "nl": "Goedenavond",
        "fil": "Magandang Gabi",
        "fr": "Bonsoir",
        "de": "Guten Abend",
        "el": "Καλησπέρα",
        "gu": "સાંજની શુભેચ્છા",
        "ha": "Barka da yamma",
        "he": "ערב טוב",
        "hu": "Jó estét",
        "id": "Selamat Malam",
        "fa": "شب بخیر",
        "pl": "Dobry wieczór",
        "pt": "Boa Noite",
        "pa": "ਸ਼ਾਮ ਦਾ ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
        "it": "Buona sera",
        "ja": "こんばんは",
        "jv": "Sugeng sonten",
        "ko": "좋은 저녁입니다",
        "ms": "Selamat Malam",
        "no": "God kveld",
        "ru": "Добрый вечер",
        "ro": "Bună seara",
        "si": "සුභ රාත්‍රියක්",
        "es": "Buenas Noches",
        "sw": "Habari za jioni",
        "sv": "God kväll",
        "ta": "மாலை வணக்கம்",
        "te": "సాయంత్ర శుభాకాంక్షలు",
        "th": "สวัสดีตอนเย็น",
        "tr": "İyi akşamlar",
        "uk": "Добрий вечір",
        "vi": "Chào buổi tối",
        "fi": "Hyvää iltaa",
        "ml": "രാത്രി വന്ദനം",
        "sk": "Dobrý večer",
        "ca": "Bona nit",
        "sr": "Добро вече",
        "hr": "Dobra večer",
        "lt": "Labas vakaras",
        "sl": "Dober večer",
        "is": "Gott kvöld",
        "eu": "Arratsalde on",
        "gl": "Boa noite",
        "mk": "Добро вечера",
        "ne": "शुभ संध्या",
        "km": "សួស្តីរាត្រី",
        "am": "ምሽት ደህና",
        "yo": "E ku irole",
        "tg": "Шамалӣ",
        "hmn": "Zoo siab",
        "fj": "Moce",
        "su": "Wilujeng wengi",
        "tt": "Кичке рәхим итегез",
        "mn": "Оройн мэнд",
        "mt": "Bongu",
        "mg": "Tsy adino",
        "wo": "Jaamu",
        "qu": "Ñukaka sumaq",
        "xh": "Ubusuku obuhle",
        "zu": "Sawubona",
        "hy": "Բարի երեկո",
        "ba": "Кичке хәерле",
        "br": "Noz",
        "se": "Buorre eahket",
        "tw": "Meda wo akye",
        "tl": "Magandang Gabi"
      }
    },
    {
      "time": "night",
      "greeting": {
        "en": "Good Night",
        "ur": "شب بخیر",
        "hi": "शुभ रात्रि",
        "ps": "ماښام مو پخير",
        "ar": "تصبح على خير",
        "bn": "শুভ রাত্রি",
        "my": "သင်လည်းကောင်းပြီ",
        "cs": "Dobrou noc",
        "zh": "晚安",
        "da": "God nat",
        "nl": "Goedenacht",
        "fil": "Magandang Gabi",
        "fr": "Bonne Nuit",
        "de": "Gute Nacht",
        "el": "Καληνύχτα",
        "gu": "રાતની શુભેચ્છા",
        "ha": "Barka da dare",
        "he": "לילה טוב",
        "hu": "Jó éjszakát",
        "id": "Selamat Malam",
        "fa": "شب بخیر",
        "pl": "Dobranoc",
        "pt": "Boa Noite",
        "pa": "ਸ਼ਾਮ ਦਾ ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
        "it": "Buona notte",
        "ja": "おやすみなさい",
        "jv": "Sugeng dalu",
        "ko": "안녕히 주무세요",
        "ms": "Selamat Malam",
        "no": "God natt",
        "ru": "Спокойной ночи",
        "ro": "Noapte bună",
        "si": "සුභ රාත්‍රියක්",
        "es": "Buenas Noches",
        "sw": "Usiku mwema",
        "sv": "God natt",
        "ta": "இரவு வணக்கம்",
        "te": "రాత్రి శుభాకాంక్షలు",
        "th": "ราตรีสวัสดิ์",
        "tr": "İyi geceler",
        "uk": "Доброї ночі",
        "vi": "Chúc ngủ ngon",
        "fi": "Hyvää yötä",
        "ml": "രാത്രി വന്ദനം",
        "sk": "Dobrú noc",
        "ca": "Bona nit",
        "sr": "Лаку ноћ",
        "hr": "Laku noć",
        "lt": "Labanakt",
        "sl": "Lahko noč",
        "is": "Gott nótt",
        "eu": "Gau on",
        "gl": "Boa noite",
        "mk": "Добро ноќ",
        "ne": "शुभ रात्रि",
        "km": "សួស្តីរាត្រី",
        "am": "የውለድ ዕለት",
        "yo": "E ku irole",
        "tg": "Шамалӣ",
        "hmn": "Zoo siab",
        "fj": "Moce",
        "su": "Wilujengwụngi",
        "tt": "Кичке рәхим итегез",
        "mn": "Оройн мэнд",
        "mt": "Bongu",
        "mg": "Tsy adino",
        "wo": "Jaamu",
        "qu": "Ñukaka sumaq",
        "xh": "Ubusuku obuhle",
        "zu": "Sawubona",
        "hy": "Բարի գիշեր",
        "ba": "Кичке хәерле",
        "br": "Noz",
        "se": "Buorre eahket",
        "tw": "Meda wo akye",
        "tl": "Magandang Gabi"
      }
    }
  ];
}
